# Generated by Django 2.2.5 on 2019-09-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehber',
            name='address',
            field=models.TextField(max_length=120),
        ),
    ]
