# Generated by Django 2.2.5 on 2019-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0002_auto_20190906_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehber',
            name='address',
            field=models.TextField(max_length=120, verbose_name='Adresi'),
        ),
        migrations.AlterField(
            model_name='rehber',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='rehber',
            name='number',
            field=models.IntegerField(verbose_name='Tel No'),
        ),
        migrations.AlterField(
            model_name='rehber',
            name='surname',
            field=models.CharField(max_length=120, verbose_name='Soyadı'),
        ),
    ]
