# Generated by Django 2.2.5 on 2019-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0004_auto_20190909_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehber',
            name='number',
            field=models.BigIntegerField(max_length=10, verbose_name='Tel No'),
        ),
    ]
